# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.ssh.private_key_path = '~/.ssh/linode_rsa'
    config.vm.provider :linode do |provider, override|
        override.vm.box = 'linode'
        override.vm.box_url = 'https://github.com/displague/vagrant-linode/raw/master/box/linode.box'
        provider.token = ENV['LINODE_TOKEN']
        provider.distribution = 'CentOS 6.5'
        if ENV["LINODE_REGION"]
            provider.datacenter = ENV["LINODE_REGION"]
        else
            provider.datacenter = 'frankfurt'
        end
        if ENV["LINODE_SIZE"]
            provider.plan = ENV["LINODE_SIZE"]
        else
            provider.plan = '4096'
        end
        if ENV["LINODE_LABEL"]
            provider.label = ENV["LINODE_LABEL"]
        else
            provider.label = 'baruwa-enterprise-edition-vagrant'
        end
    end
    config.vm.provision "shell" do |s|
        s.path = "scripts/provision.py"
        s.args = [ENV["BARUWA_ACTIVATION_KEY"]]
    end
end
